### PR TITLE
db container image fix & update vault image to 1.8.1

### PR DESCRIPTION
**Pull request by joshua-bradley**
the old compose file failed to build db image.  So updated dotnet secrets code base to use new mssql image hosted in the msft container reg.  Also bumped the vault image to 1.8.1

### CODE REVIEW

**Comment by joshua-bradley** [comment]
fyi - committed the fix from my laptop without signing into the repo when I cloned it so nanos maxim is my local user.  Let me know if you need me to resubmit branch under the gh user

**Comment by yhyakuna** [comment]
@joshua-bradley  Please sign the CLA. Thanks. 🙏

**Comment by joshua-bradley** [comment]
> @joshua-bradley Please sign the CLA. Thanks. 🙏

hi @yhyakuna  - as per my [comment](https://github.com/hashicorp/vault-guides/pull/362#issuecomment-920370195) I can't sign the CLA for "nano-maxim" as that's just my laptop user.  I have however for my gh-user.  should I resubmit the branch more cleanly and re-create the PR??

**Comment by yhyakuna** [comment]
> hi @yhyakuna - as per my [comment](https://github.com/hashicorp/vault-guides/pull/362#issuecomment-920370195) I can't sign the CLA for "nano-maxim" as that's just my laptop user. I have however for my gh-user. should I resubmit the branch more cleanly and re-create the PR??

Sorry, I missed the comment.  Yes, if you don't mind, could you resubmit it again?  We cannot proceed until the CLA is signed.

**Comment by kalafut** [comment]
@joshua-bradley Might as well update to image 1.8.3 now too.

**Pull request closed without merging**
