### PR TITLE
Add demo ACL policy for OIDC auth guide

### PR DESCRIPTION
**Pull request by Lynty**
A prerequisite to configuring OIDC auth for Vault is to author and create a policy named `demo`. This update adds instructions on doing this.

Also solves #164

### CODE REVIEW

**Comment by rahulkohli23** [comment]
Hi @Lynty ,
I tried creating a new ACL policy as described by you but I'm still facing an issue while trying to login using OIDC.
Though i'm to login through Keycloak instead of Google but the process is same.
below is the screenshot of my login attempt using OIDC.
let me know if u can help me resolve this.

image

any leads would be appreciated.

**Comment by Lynty** [comment]
hi @rahulkohli23,

Can you verify a couple things for me?
1. Can you show me the policy you wrote to Vault by running `vault policy read <policyname>`? What is your policy name?
2. What did you name your Vault role and can you paste your configuration by running `vault read auth/oidc/role/<rolename>`

**Comment by rahulkohli23** [comment]
Hi @Lynty 

Below are the details u asked for

```
vault policy read demo
path "/secret/*" {
capabilities = ["create", "read", "update", "delete", "list"]
}

```
Role Details

```
vault read auth/oidc/role/demo
Key                        Value
---                        -----
allowed_redirect_uris      [[http://127.0.0.1:8200//ui/vault/auth/oidc/oidc/callback]]
bound_audiences            [[vault-local]]
bound_claims               <nil>
bound_subject              n/a
claim_mappings             <nil>
clock_skew_leeway          0
expiration_leeway          0
groups_claim               n/a
not_before_leeway          0
oidc_scopes                <nil>
policies                   [demo]
role_type                  oidc
token_bound_cidrs          []
token_explicit_max_ttl     0s
token_max_ttl              0s
token_no_default_policy    false
token_num_uses             0
token_period               0s
token_policies             [demo]
token_ttl                  1h
token_type                 default
ttl                        1h
user_claim                 sub
verbose_oidc_logging       false

```

Hope this will be helpful to diagnose

**Comment by Lynty** [comment]
@rahulkohli23 I am not familiar with Keycloak but for GSuite, it is not possible to set up OIDC with a local redirect uri `127.0.0.1`. I will attempt to set up OIDC with Keycloak later to see if I can replicate the issue.

**Comment by rahulkohli23** [comment]
@Lynty 
what should be the value for redirect url in case of G-Suite, when I'm running vault on my local machine ?
may be that can help me fix this.

**Comment by Lynty** [comment]
@rahulkohli23 
Mine looks like this
`https://test.test.com:<testport>/ui/vault/auth/oidc/oidc/callback`

**Comment by Lynty** [comment]
@rahulkohli23 
What if instead of having 
```
allowed_redirect_uris      [[http://127.0.0.1:8200//ui/vault/auth/oidc/oidc/callback]]
```
doing this instead:
```
allowed_redirect_uris      [http://127.0.0.1:8200/ui/vault/auth/oidc/oidc/callback]
```
> Note the single brackets around the uri as well as removing a `/` after the port

Make sure `http://127.0.0.1:8200/ui/vault/auth/oidc/oidc/callback` is reflected on Keycloak's side

**Pull request closed without merging**
